version: '3.11.5'
services:
  django:
    container_name: myapp
    build: .
    ports:
      -"8000:8000"
    entrypoint: 
      -PG_USER=postgres
      -PG_PASSWORD=postgres
      -PG_DB=postgres
      -PG_HOST=db
      -PG_USER=5432
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pddata:{}